### ISSUE TITLE
Nice-to-have AEL settings

### ISSUE THREAD

**Issue by Scall** [Wintermute0110/plugin.program.advanced.MAME.launcher#3]
These advanced settings are currently available in AEL, but not in AML, I hope you will consider adding them:

Action on Kodi playing media
After/before launch delay (ms)
Suspend/resume Kodi audio engine

**Comment by Wintermute0110** [comment]
Thanks for reporting. Will code ASAP!

**Comment by Wintermute0110** [comment]
Implemented in 0.9.7. I will close the issue now. Reopen if you find any problems.
